name: Daily Tender Check

on:
  workflow_dispatch:

  schedule:
    # Pokreće se svakog dana u 06:00 UTC
    # To je 08:00 ljeti u Crnoj Gori
    # i 07:00 zimi
    - cron: "0 6 * * *"

jobs:
  tender-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run CEJN Tender Monitor
        env:
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: |
          python daily_tender_check.py
